import os

class Config:
    SECRET_KEY = os.urandom(24)
    CLIENT_ID = os.getenv('CLIENT_ID')
    CLIENT_SECRET = os.getenv('CLIENT_SECRET')
    CALLBACK_URL = os.getenv('CALLBACK_URL')
    TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
    TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')
    DATABASE_URL = os.getenv('DATABASE_URL')
    DEFAULT_MIN_DELAY = int(os.getenv("BULK_POST_MIN_DELAY", 2))
    DEFAULT_MAX_DELAY = int(os.getenv("BULK_POST_MAX_DELAY", 10))

# For direct imports
CLIENT_ID = Config.CLIENT_ID
CLIENT_SECRET = Config.CLIENT_SECRET
CALLBACK_URL = Config.CALLBACK_URL
TELEGRAM_BOT_TOKEN = Config.TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID = Config.TELEGRAM_CHAT_ID
DATABASE_URL = Config.DATABASE_URL
DEFAULT_MIN_DELAY = Config.DEFAULT_MIN_DELAY
DEFAULT_MAX_DELAY = Config.DEFAULT_MAX_DELAY
